### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/pandadocs#1]
Since this looks to be static html, it can be hosted right on github by creating a gh-pages branch. It would then be almost immediately available at lullabot.github.io/pandadocs - perhaps that's not the intent here (i'm still not quite sure what this is yet) but thought i'd alert you to the possibility.

**Comment by jwitkowski79** [comment]
Thanks @sirkitree! The sales team is using a new tool called Panda Docs to create and track proposals for development. The templates that they provide are just awful. There's a way that we can add custom CSS so I'm going to help them out and see if I can improve the design of the default template. We thought it would be a good idea to create a repo just in case anything has to be updated in the future. Not sure if we need a gh-pages branch but it's nice to know that I have the option!

**Comment by sirkitree** [comment]
Cool! Good luck!
